name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_IPNS_CID: ${{ vars.TEST_IPNS_CID }}
          TEST_IPNS_PRIVATE_KEY: ${{ secrets.TEST_IPNS_PRIVATE_KEY }}
